/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "LinkedList.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_CreateEmptyList();
extern void test_SetPrintElemFunc();
extern void test_SetCopyElemFunc();
extern void test_SetCompareElemFunc();
extern void test_IsListInitialized();
extern void test_InsertFront();
extern void test_InsertBack();
extern void test_InsertAfter();


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("../MyGenericTestProgram/tests/test_LinkedList.c");
  run_test(test_CreateEmptyList, "test_CreateEmptyList", 7);
  run_test(test_SetPrintElemFunc, "test_SetPrintElemFunc", 12);
  run_test(test_SetCopyElemFunc, "test_SetCopyElemFunc", 17);
  run_test(test_SetCompareElemFunc, "test_SetCompareElemFunc", 22);
  run_test(test_IsListInitialized, "test_IsListInitialized", 27);
  run_test(test_InsertFront, "test_InsertFront", 32);
  run_test(test_InsertBack, "test_InsertBack", 37);
  run_test(test_InsertAfter, "test_InsertAfter", 42);

  return UNITY_END();
}
